### PR TITLE
detect editor when opening a portal

### PR DESCRIPTION
**Pull request by timothypratley**
checks the .portal folder for files created by editors when launching portal plugins.

### CODE REVIEW

**Comment by daslu** [comment]
That is really nice & elegant. 

A couple of comments:
1. It doesn't seem to detect vscode in my system (haven't tried to understand why yet).
3. After this change, the naming distinction `open` / `open-if-needed` does not make sense anymore. Maybe they should be both supported by the same function with a different number of arguments.

**Comment by timothypratley** [comment]
Thanks for trying it @daslu

1. Please look in the `.portal` directory and see if perhaps there is an "emacs" file taking priority? Possibly you have portal already open? Or maybe missing the vs-code.edn file due to not having the plugin?? 🤔 

This is what I see in vs-code:
Screen Shot 2023-09-03 at 8 44 41 AM

2. Good thinking, I updated it like you suggested.

**Comment by daslu** [comment]
Thanks!

I could not see a `.portal` subdirectory.

Anyway, I'll merge it, and we'll continue exploring.

**Review by daslu — COMMENTED** [review]
(sorry, should have written my previous comments here at the "review" box)

**Pull request merged**
